version: '3'

services:
  frontend:
    build: ./frontend
    ports:
      - "8085:8085"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:3000

  backend:
    build: ./backend
    ports:
      - "3000:3000"